apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 2
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: registry.gitlab.com/etiennepeiniau/spring-cloud-netflix-test-config-server
          ports:
            - containerPort: 8888
      imagePullSecrets:
            - name: regcred